shiftstack/bugwatcher

Containerfile
We frequently see the bugwatcher job fail to build the container image
due to the inability to fetch these repositories.
Disable them as they're not needed.
The usual way to disable the repositories with DNF would be to use the
`dnf config-manager --set-disabled` command, however it is part of
dnf-plugins-core package that is not installed in the fedora container
image. Instead we modify the repository files directly with `sed`.
=> Disable unnecessary repositories

main.py
With this patch, the bugwatcher starts assigning bugs with the
subcomponent "platform-openstack" of "Machine Config Operator".
=> Add machine-config-operator "platform-openstack"

pretriage/Containerfile, pretriage/dnf_safe
Like we did for shiftstack-ci, let's have a small util to use DNF in
retry mode, which will avoid some CI errors when Fedora repos are
unavailable at that time.
=> Safe usage of DNF for CI

pretriage/main.py, pretriage/requirements.txt
With this patch, the random selection of a team member does not rely on
internal entropy sources, which may be hard to get in a containerised
environment. The PRNG is now seeded using nanosecond time from NTP.
=> pretriage: Ensure randomness

posttriage.py, pretriage.py, setup.cfg
Among other uses, could make up for a presubmit dry-run in the CI.
=> Add an online help

posttriage.py
Part of the BZ comment message was not interpreted because it lacked the ‘f’ for string interpolation:
> Removing the Triaged keyword because:
> {reasons}
=> Fix posttriage reasons

doctext.py
Prior to this patch, the query for `doctext` looked for verified and
closed bugs targeting 4.10. With this change, the query does not check
the target version any more; instead, it only returns bugs in VERIFIED
or ON_QA.
Note that with this patch, the bugs in CLOSED state are no longer in
scope.
=> doctext: Fetch all target releases

pretriage.py
Allow us to specify component "specializations", so that e.g. the Kuryr folks get Kuryr bugs. This will allow us to unify the separate teams in a single bug triage.
=> Assign bugs based on component specialization

cmd/pretriage/main.go
The component `Machine Config Operator/Machine Config Operator` was
apparently removed from the Jira OCPBUGS project.
=> pretriage: Drop non-existant component

README.md, cmd/pretriage/main.go, cmd/pretriage/team.go, doctext.py, pretriage.py
Depends on: https://github.com/openshift/release/pull/31064
Introduce a new optional environment variable: `TEAM_VACATION`. Team members in vacation state won't be assigned triage.
=> pretriage: Do not assign to vacating team members

pretriage.py
`datetime.fromisoformat` is not available in Python 3.6.
=> pretriage.py: Parse time with Python 3.6

cmd/doctext/notify.go
For that's how the "doctext" field is called in Jira.
=> doctext: Call it "Release Note Text" in Jira

cmd/doctext/main.go, cmd/posttriage/main.go
This will only match if the issue has osp or openstack in its summary.
=> Add MCO platform-none component to doctext and posttriage search

cmd/doctext/notify.go, cmd/doctext/team.go, cmd/triage/notify.go, cmd/triage/team.go
Mentioning a [user group][1] requires a different format from mentioning a [user][2].
[1]: https://api.slack.com/reference/surfaces/formatting#mentioning-groups
[2]: https://api.slack.com/reference/surfaces/formatting#mentioning-users
=> Use user group ID for team notifications

cmd/pretriage/main.go, cmd/pretriage/team.go
Also, with this patch the pretriage's team logic is made more compatible with the other bugwatcher bot's team logic, so that we can hopefully extract team logic to a separate package soon.
=> pretriage: Handle the case where no team member is available

cmd/doctext/checks.go
issues.redhat.com is using a new custom field, `customfield_12317313`, for `Release Note Text`. The old one, `customfield_12310211`, is now called `Release Note Text_Old`. You can view this at https://issues.redhat.com/rest/api/latest/field (per the [JIRA KB](https://confluence.atlassian.com/jirakb/how-to-find-any-custom-field-s-ids-744522503.html)).
=> doctext: Change custom field

cmd/doctext/checks.go
As noted previously, issues.redhat.com is using a new custom field, `customfield_12317313`, for 'Release Note Text'. However, it's also using a wholly new custom field, `customfield_12320850` or 'Release Note Type'. This can be set to various values, one of which is 'No Doc Update'. If set to this value, clearly we can get away with no setting the 'Release Note Text' field.
=> doctext: Also consider Release Note Type

.gitignore, cmd/triage/main.go, cmd/triage/tasker/tasker.go
Incapsulate the assignee map in a type and protect it with a mutex to avoid concurrent writes.
=> Fix concurrent map access

cmd/doctext/checks.go
We were treating it as a string, having misread the relevant code in go-jira. Correct this oversight.
=> doctext: Release note type is an object

cmd/pretriage/main.go
If the parent issue doesn't have an assignee, ignore the parent issue.
=> Handle unassigned parent issues

cmd/triage/main.go
We can consider any bug that has the "Need Info From" field set to not require triage yet, since we're waiting on info from the requestee. Note that we don't filter out team members from this and instead look for *any* needinfo. This has the potential to cause false positives if the needinfo is on one of the team members, but that seems like an acceptable risk given said team member will be getting notifications. It also allows us to do this via the query rather than filtering issues and we work through them.
=> triage: Ignore bugs with needinfo

cmd/posttriage/checks.go
We have been missing warnings since a while ago: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/periodic-ci-shiftstack-bugwatcher-main-bugwatcher-posttriage/1756211528622673920/artifacts/bugwatcher-posttriage/shiftstack-bugwatcher-posttriage/build-log.txt
=> posttriage: Release blocker is no longer an array

cmd/pretriage/main.go
Treat bugs assigned to the bot as if they were unassigned. That is: reassign bugs that are assigned to the bot.
@stephenfin would this solve the problem for which you wrote https://github.com/shiftstack/bugwatcher/pull/65?
=> pretriage: Reassign bugs assigned to the bot

cmd/pretriage/main.go
Only look for bugs who haven't set had these fields set yet.
=> Don't auto-set fields on ART bug repeatedly

cmd/pretriage/main.go
Turn comments into runtime logs.
The [current logs](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/periodic-ci-shiftstack-ci-main-bugwatcher-pretriage/1803806554701434880/artifacts/bugwatcher-pretriage/shiftstack-bugwatcher-pretriage/build-log.txt) are a bit arid:
```plaintext
2024/06/20 15:06:29 Incoming batch of 0 issues
2024/06/20 15:06:30 Incoming batch of 0 issues
```
=> pretriage: Use logs to advertise the two operations

Makefile, README.md
Build all binaries with `make`. Run pretriage with `make run-pretriage`
=> Makefile: `make` should build, not run

cmd/posttriage/checks.go
Added a conditional check to handle cases where the resolution field is nil, preventing potential nil pointer dereference. The string returned in the error message might need to be updated
=> Fix nil pointer dereference in priorityCheck function

pkg/query/query.go
To track all pertinent bugs, our Jira board historically has two parts:
* include all OCPBUGS issues with our components
* include all OCPBUGS with components adjacent to ours, and with "openstack" in the summary
In Bugzilla, this was useful.
However, the second part of the query only seems to catch false positives lately.
This commit removes the second part, simplifying the bug query to just trust the Component assignment of the bug.
=> Simplify bug query

cmd/doctext/main.go, cmd/posttriage/main.go, cmd/pretriage/main.go, cmd/triage/main.go, pkg/jiraclient/jiraclient.go
Our corporate Jira instance has implemented request throttling. This change introduces retries.
=> Retry when hitting 429 TooManyRequests

cmd/doctext/main.go, cmd/doctext/notify.go, cmd/pretriage/main.go, cmd/pretriage/notify.go, cmd/triage/main.go, cmd/triage/notify.go, pkg/slack/slack.go
Moving the Slack logic to its own package.
=> refactor: dry up sending Slack messages

pkg/team/team.go
Make sure that when searching for a person using the empty string as the key, no result is returned.
=> Address case where person has no Github handle

cmd/posttriage/checks.go, cmd/posttriage/main.go
The field is not currently used actively enough to warrant the overhead it generates on bug triage.
=> OSASINFRA-3918: posttriage: Remove check for Test coverage
